# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

# Using set to automatically remove repititions
terms = set([i**j for i in range(2, 101) for j in range(2, 101)])
# Output
print("There are %d terms." % ( len(terms) ))